### PR TITLE
refactor the existing dux module, add child dux and fix the test code

### LINKED ISSUE #189: Refactor the Client, Household, Child dux module using baseClient.ts
Currently, the dux modules related to the client are separated from each other and don't inherit the common operation from anywhere. but now we have an abstract file for all those common operations, need to use that as a parent file. clients, household, child register, all of their dux modules should be similar to the ANC module. Create PR for each of the dux modules for refactoring.

### PR DESCRIPTION
**Pull request by prodhan29**
This PR closes #189 and closes  #171 
The following things are present in the PR:
- refactor the client dux module, household dux module
- fix test code for client and household dux module 
- add child-dux module
- add test code for child-dux

### CODE REVIEW

File: clients/core/src/store/ducks/child.ts [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+export const fetchChildList = fetchClientsFactory<Child>(reducerName);
+export const removeChildList = removeClientsFactory(reducerName);
+export const setTotalRecords = setTotalRecordsFactory(reducerName);
+
+// selectors
+export const getChildListById = getClientsByIdFactory<Child>(reducerName);
+export const getChildArray = getClientsArrayFactory<Child>(reducerName);
+export const getChildById = getClientByIdFactory<Child>(reducerName);
+
+export function getTotalRecords(state: Partial<Store>): number {
```
Comment (p-netm) [inline clients/core/src/store/ducks/child.ts]: I believe there is also a factory for this. `getTotalRecordsFactory`

File: clients/core/src/store/ducks/households.ts [hunk 2]
```diff
@@ -1,136 +1,36 @@
...
- */
-export function getHouseholdById(state: Partial<Store>, id: string): Household | null {
-    return get(getHouseholdsById(state), id) || null;
-}
-
-/** returns the count of all records present in server
- * @param {Partial<Store>} state - the redux store
- * @return { number } - total records value from the store
- */
 export function getTotalRecords(state: Partial<Store>): number {
```
Comment (p-netm) [inline clients/core/src/store/ducks/households.ts]: I believe there is also a factory for this. getTotalRecordsFactory

File: clients/core/src/store/ducks/clients.ts [hunk 3]
```diff
@@ -31,114 +33,20 @@ export interface Client {
...
-}
-
-/** get a specific client by their id
- * @param {Partial<Store>} state - the redux store
- * @return {Client | null} a client obj if the id is found else null
- */
-export function getClientById(state: Partial<Store>, id: string): Client | null {
-    return get(getClientsById(state), id) || null;
-}
+export default reducer;
```
Comment (p-netm) [inline clients/core/src/store/ducks/clients.ts]: do we also want to include the `TotalRecords` actions and selectors here?

File: clients/core/src/store/ducks/child.ts [hunk 4]
```diff
@@ -0,0 +1,36 @@
...
+    getClientsByIdFactory,
+    getClientsArrayFactory,
+    getClientByIdFactory,
+} from './baseClients';
+import { Store } from 'redux';
+
+/** The reducer name */
+export const reducerName = 'opensrp-web/client-type/child';
+
+/** Interface for household object same as client */
```
Comment (p-netm) [inline clients/core/src/store/ducks/child.ts]: <del>household</del>

File: clients/core/src/store/ducks/tests/child.test.ts [hunk 5]
```diff
@@ -0,0 +1,67 @@
...
+    it('sets total records', () => {
+        store.dispatch(setTotalRecords(3));
+        let numberOfRecords = getTotalRecords(store.getState());
+        expect(numberOfRecords).toEqual(3);
+
+        store.dispatch(setTotalRecords(0));
+        numberOfRecords = getTotalRecords(store.getState());
+        expect(numberOfRecords).toEqual(0);
+    });
+});
```
Comment (p-netm) [inline clients/core/src/store/ducks/tests/child.test.ts]: Nice
1 trivial test scenario that i think we are missing and can be a nice to have; is to to make sure dispatching the same object more than once adds  it only once to a specified store slice.

```typescript
    it('Adds new child-list to store instead of overwriting existing ones', () => {
        store.dispatch(fetchChildList([fixtures.child1, fixtures.child2]));
        let numberOfChild = getChildArray(store.getState()).length;
        expect(numberOfChild).toEqual(2);

        store.dispatch(fetchChildList([fixtures.child3]));
        numberOfChild = getChildArray(store.getState()).length;
        expect(numberOfChild).toEqual(3);
        
       store.dispatch(fetchChildList([fixtures.child1]));
        let numberOfChild = getChildArray(store.getState()).length;
        expect(numberOfChild).toEqual(3);
    });
```

I hope you don't mind adding this to the baseClients tests as well,

File: clients/core/src/store/ducks/clients.ts [hunk 6]
```diff
@@ -31,114 +33,20 @@ export interface Client {
...
-            return SeamlessImmutable({
-                ...state,
-                clientsById: action.clientsById,
-            });
-        default:
-            return state;
-    }
-}
+// action
+/** actionCreator returns action to to add anc records to store */
```
Comment (p-netm) [inline clients/core/src/store/ducks/clients.ts]: Tiny cleanup here in the docstring <del> anc <del>

File: clients/core/src/store/ducks/child.ts (hunk 1 above)
Comment (prodhan29) [reply clients/core/src/store/ducks/child.ts]: didn't notice that at first. updated the code with `getTotalRecordsFactory`

File: clients/core/src/store/ducks/child.ts (hunk 4 above)
Comment (prodhan29) [reply clients/core/src/store/ducks/child.ts]: done

File: clients/core/src/store/ducks/tests/child.test.ts (hunk 5 above)
Comment (prodhan29) [reply clients/core/src/store/ducks/tests/child.test.ts]: Added a test case in baseClient. to make sure same object won't get saved twice.

File: clients/core/src/store/ducks/clients.ts (hunk 6 above)
Comment (prodhan29) [reply clients/core/src/store/ducks/clients.ts]: done.
